create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  project_title text not null default '',
  work_date date not null unique,
  team text not null default '',
  work_mode text not null default '',
  clock_in text,
  clock_out text,
  break_minutes integer,
  follow_up text not null default '',
  updates text not null default '',
  created_at timestamp with time zone not null default now()
);

alter table public.attendance_records enable row level security;

create policy "Allow public read attendance records"
on public.attendance_records
for select
to anon
using (true);

create policy "Allow public insert attendance records"
on public.attendance_records
for insert
to anon
with check (true);

create policy "Allow public update attendance records"
on public.attendance_records
for update
to anon
using (true)
with check (true);

create policy "Allow public delete attendance records"
on public.attendance_records
for delete
to anon
using (true);
